FreeLing: semanticDB Class Reference
semanticDB Class Reference
Class semanticDB implements a semantic DB interface.
#include <semdb.h>
Public Member Functions
semanticDB (const std::string &, const std::string &)
Constructor.
~semanticDB ()
Destructor.
std::list< std::string > get_sense_words (const std::string &, const std::string &)
get list of words for a sense+pos
std::list< std::string > get_word_senses (const std::string &, const std::string &)
get list of senses for a lemma+pos
sense_info get_sense_info (const std::string &, const std::string &)
get sense info for a sensecode+pos
Private Attributes
database sensesdb
C++ Interface to BerkeleyDB C API.
database wndb
Detailed Description
Class semanticDB implements a semantic DB interface.
Constructor & Destructor Documentation
semanticDB::semanticDB (const std::string & SensesFile, const std::string & WNFile)
Constructor.
Create the sense annotator.
References database::open_database(), sensesdb, TRACE, and wndb.
semanticDB::~semanticDB ()
Destructor.
Destroy sense annotator module, close database.
References database::close_database(), sensesdb, and wndb.
Member Function Documentation
sense_info semanticDB::get_sense_info (const std::string & , const std::string &)
get sense info for a sensecode+pos
Referenced by check_asynon::eval(), check_synon::eval(), check_semfile::eval(), and check_tonto::eval().
std::list<std::string> semanticDB::get_sense_words (const std::string & , const std::string &)
get list of words for a sense+pos
std::list<std::string> semanticDB::get_word_senses (const std::string & , const std::string &)
get list of senses for a lemma+pos
Referenced by senses::analyze(), check_asynon::eval(), check_synon::eval(), check_semfile::eval(), and check_tonto::eval().
Member Data Documentation
database semanticDB::sensesdb [private]
C++ Interface to BerkeleyDB C API.
Referenced by semanticDB(), and ~semanticDB().
database semanticDB::wndb [private]
Referenced by semanticDB(), and ~semanticDB().
The documentation for this class was generated from the following files:
semdb.h
semdb.cc