FreeLing: accents_es Class Reference
accents_es Class Reference
Derived accents_module for Spanish accentuation.
#include <accents_modules.h>
Public Member Functions
accents_es ()
Constructor.
void fix_accentuation (std::set< std::string > &, const sufrule &) const
Specific accentuation patterns for Spanish.
Static Private Member Functions
static bool is_vowel (char)
check for a vowel (maybe with latin accents)
static bool is_vowel_notacc (char)
check for a vowel (strictly)
static bool is_monosylabic (const std::string &)
check monosyllabous word
static bool is_open (char)
check for weak spanish vowels
static bool is_accentued_esp (char)
check for spanish accents
static bool is_accentued_esp (const std::string &)
check for spanish accents
static void remove_accent_esp (std::string &)
remove spanish accents
static void remove_accent_esp (char &)
remove spanish accents
static void put_accent_esp (char &)
set spanish accents
static bool put_accent_esp (std::string &)
set spanish accents
static bool llana_acentuada (const std::string &)
check for spanish accent pattern: "palabras llanas acentuadas"
static bool aguda_mal_acentuada (const std::string &)
check for spanish accent pattern: "palabras agudas mal acentuadas"
Detailed Description
Derived accents_module for Spanish accentuation.
Constructor & Destructor Documentation
accents_es::accents_es ()
Constructor.
Create an accent handler for Spanish.
References TRACE.
Member Function Documentation
bool accents_es::aguda_mal_acentuada (const std::string & p) [static, private]
check for spanish accent pattern: "palabras agudas mal acentuadas"
References is_accentued_esp(), and is_vowel().
void accents_es::fix_accentuation (std::set< std::string > & , const sufrule &) const [virtual]
Specific accentuation patterns for Spanish.
Implements accents_module.
bool accents_es::is_accentued_esp (const std::string & s) [static, private]
check for spanish accents
References is_accentued_esp().
bool accents_es::is_accentued_esp (char c) [static, private]
check for spanish accents
Referenced by aguda_mal_acentuada(), is_accentued_esp(), is_monosylabic(), and llana_acentuada().
bool accents_es::is_monosylabic (const std::string & p) [static, private]
check monosyllabous word
References is_accentued_esp(), is_open(), and is_vowel().
bool accents_es::is_open (char c) [static, private]
check for weak spanish vowels
Referenced by is_monosylabic(), and llana_acentuada().
bool accents_es::is_vowel (char c) [static, private]
check for a vowel (maybe with latin accents)
Referenced by aguda_mal_acentuada(), is_monosylabic(), and llana_acentuada().
bool accents_es::is_vowel_notacc (char c) [static, private]
check for a vowel (strictly)
Referenced by put_accent_esp().
bool accents_es::llana_acentuada (const std::string & p) [static, private]
check for spanish accent pattern: "palabras llanas acentuadas"
References is_accentued_esp(), is_open(), and is_vowel().
bool accents_es::put_accent_esp (std::string & s) [static, private]
set spanish accents
References is_vowel_notacc(), and put_accent_esp().
void accents_es::put_accent_esp (char & c) [static, private]
set spanish accents
Referenced by put_accent_esp().
void accents_es::remove_accent_esp (char & c) [static, private]
remove spanish accents
void accents_es::remove_accent_esp (std::string & s) [static, private]
remove spanish accents
The documentation for this class was generated from the following files:
accents_modules.h
accents_modules.cc