FreeLing: traces Class Reference
traces Class Reference
MOD_TRACECODE and MOD_TRACENAME are empty.
#include <traces.h>
Static Public Member Functions
static void error_crash (const std::string &, const std::string &, unsigned long)
static trace methods definition. Inlined for efficiency
static void warning (const std::string &, const std::string &, unsigned long)
static void trace (int, const std::string &, const std::string &, unsigned long)
static void trace_word (int lv, const word &, const std::string &, unsigned long)
static void trace_word_list (int, const std::list< word > &, const std::string &, unsigned long)
static void trace_sentence (int, const sentence &, const std::string &, unsigned long)
static void trace_sentence_list (int, const std::list< sentence > &, const std::string &, unsigned long)
Static Public Attributes
static int TraceLevel = 0
Static data members.
static unsigned long TraceModule = 0x0000000
Detailed Description
MOD_TRACECODE and MOD_TRACENAME are empty.
The class using the trace is expected to set them Class traces implements trace and error handling utilities.
Member Function Documentation
void traces::error_crash (const std::string & msg, const std::string & modname, unsigned long modcode) [inline, static]
static trace methods definition. Inlined for efficiency
void traces::trace (int lv, const std::string & msg, const std::string & modname, unsigned long modcode) [inline, static]
References TraceLevel, and TraceModule.
Referenced by trace_sentence(), and trace_word().
void traces::trace_sentence (int lv, const sentence & s, const std::string & modname, unsigned long modcode) [inline, static]
References trace(), trace_word(), TraceLevel, and TraceModule.
Referenced by trace_sentence_list().
void traces::trace_sentence_list (int lv, const std::list< sentence > & ls, const std::string & modname, unsigned long modcode) [inline, static]
References trace_sentence(), TraceLevel, and TraceModule.
void traces::trace_word (int lv, const word & wd, const std::string & modname, unsigned long modcode) [inline, static]
References trace().
Referenced by trace_sentence(), and trace_word_list().
void traces::trace_word_list (int lv, const std::list< word > & wl, const std::string & modname, unsigned long modcode) [inline, static]
References trace_word(), TraceLevel, and TraceModule.
void traces::warning (const std::string & msg, const std::string & modname, unsigned long modcode) [inline, static]
Member Data Documentation
int traces::TraceLevel = 0 [static]
Static data members.
They are global variables, declared here in a separate module so it is linked only once.
Referenced by trace(), trace_sentence(), trace_sentence_list(), and trace_word_list().
unsigned long traces::TraceModule = 0x0000000 [static]
Referenced by trace(), trace_sentence(), trace_sentence_list(), and trace_word_list().
The documentation for this class was generated from the following files:
traces.h
traces.cc