FreeLing: accents Class Reference
accents Class Reference
The class accents provides a wrapper to transparently create and access an accents_module to handle accentuation for the appropriate language.
#include <accents.h>
Public Member Functions
accents (const std::string &)
Constructor.
~accents ()
Destructor.
void fix_accentuation (std::set< std::string > &, const sufrule &) const
fix accentuation patterns of a list of root candidates, according to a suffix rule
Private Attributes
accents_module * who
remember which module is doing the real work.
Detailed Description
The class accents provides a wrapper to transparently create and access an accents_module to handle accentuation for the appropriate language.
Constructor & Destructor Documentation
accents::accents (const std::string & Lang)
Constructor.
Create the appropriate accents_module (according to received options), and create a wrapper to access it.
Create Spanish accent handler
Create Galician accent handler !! (equal to Spanish ??) !!
Create Catalan accent handler !! To be fixed !!
Create Default (null) accent handler. Ok for english.
References who.
accents::~accents ()
Destructor.
Destroy the wrapper and the wrapped accents_module.
References who.
Member Function Documentation
void accents::fix_accentuation (std::set< std::string > & candidates, const sufrule & suf) const
fix accentuation patterns of a list of root candidates, according to a suffix rule
wrapper methods: just call the wrapped accents_module.
References accents_module::fix_accentuation(), and who.
Referenced by affixes::look_for_affixes_in_list(), and affixes::look_for_combined_affixes().
Member Data Documentation
accents_module* accents::who [private]
remember which module is doing the real work.
Referenced by accents(), fix_accentuation(), and ~accents().
The documentation for this class was generated from the following files:
accents.h
accents.cc