FreeLing: check_semfile Class Reference
check_semfile Class Reference
lemma has given WN semantic file
#include <dep_rules.h>
Public Member Functions
check_semfile (semanticDB &, const std::string &, const std::string &)
bool eval (dep_tree::iterator) const
eval whether a single node matches a condition only called from check if needed.
Private Attributes
semanticDB & semdb
Detailed Description
lemma has given WN semantic file
Constructor & Destructor Documentation
check_semfile::check_semfile (semanticDB & , const std::string & , const std::string &)
Member Function Documentation
bool check_semfile::eval (dep_tree::iterator n) const [virtual]
eval whether a single node matches a condition only called from check if needed.
The abstract class version should never be reached.
Reimplemented from rule_expression.
References rule_expression::find(), semanticDB::get_sense_info(), semanticDB::get_word_senses(), semdb, and sense_info::semfile.
Member Data Documentation
semanticDB& check_semfile::semdb [private]
Referenced by eval().
The documentation for this class was generated from the following files:
dep_rules.h
dep_rules.cc