FreeLing: FlexLexer Class Reference
FlexLexer Class Reference
#include <FlexLexer.h>
Public Member Functions
virtual ~FlexLexer ()
const char * YYText ()
int YYLeng ()
virtual void yy_switch_to_buffer (struct yy_buffer_state *new_buffer)=0
virtual struct yy_buffer_state * yy_create_buffer (istream *s, int size)=0
virtual void yy_delete_buffer (struct yy_buffer_state *b)=0
virtual void yyrestart (istream *s)=0
virtual int yylex ()=0
int yylex (istream *new_in, ostream *new_out=0)
virtual void switch_streams (istream *new_in=0, ostream *new_out=0)=0
int lineno () const
int debug () const
void set_debug (int flag)
Protected Attributes
char * yytext
int yyleng
int yylineno
int yy_flex_debug
Constructor & Destructor Documentation
virtual FlexLexer::~FlexLexer () [inline, virtual]
Member Function Documentation
int FlexLexer::debug () const [inline]
References yy_flex_debug.
int FlexLexer::lineno () const [inline]
References yylineno.
void FlexLexer::set_debug (int flag) [inline]
References yy_flex_debug.
virtual void FlexLexer::switch_streams (istream * new_in = 0, ostream * new_out = 0) [pure virtual]
Implemented in yyFlexLexer.
Referenced by yylex().
virtual struct yy_buffer_state* FlexLexer::yy_create_buffer (istream * s, int size) [read, pure virtual]
Implemented in yyFlexLexer.
virtual void FlexLexer::yy_delete_buffer (struct yy_buffer_state * b) [pure virtual]
Implemented in yyFlexLexer.
virtual void FlexLexer::yy_switch_to_buffer (struct yy_buffer_state * new_buffer) [pure virtual]
Implemented in yyFlexLexer.
int FlexLexer::YYLeng () [inline]
References yyleng.
int FlexLexer::yylex (istream * new_in, ostream * new_out = 0) [inline]
References switch_streams(), and yylex().
virtual int FlexLexer::yylex () [pure virtual]
Implemented in yyFlexLexer.
Referenced by yylex().
virtual void FlexLexer::yyrestart (istream * s) [pure virtual]
Implemented in yyFlexLexer.
const char* FlexLexer::YYText () [inline]
References yytext.
Member Data Documentation
int FlexLexer::yy_flex_debug [protected]
Referenced by debug(), and set_debug().
int FlexLexer::yyleng [protected]
Referenced by YYLeng().
int FlexLexer::yylineno [protected]
Referenced by lineno().
char* FlexLexer::yytext [protected]
Referenced by YYText().
The documentation for this class was generated from the following file:
FlexLexer.h