FreeLing: simplesearch Class Reference
simplesearch Class Reference
#include <simplesearch.h>
Classes
class comparator
Public Member Functions
simplesearch (string const _scores, string const _corpus)
void search (char *const _s, const int _length, const int _debug)
~simplesearch ()
Static Private Member Functions
static int max (const int &a, const int &b)
static int min (const int &a, const int &b)
Private Attributes
aligner< int > * al
golem * g
string corpus
priority_queue< aligner< int >
::alin *, vector< aligner< int >
::alin * >, comparator > heap
Constructor & Destructor Documentation
simplesearch::simplesearch (string const _scores, string const _corpus) [inline]
References al, and corpus.
simplesearch::~simplesearch () [inline]
References al.
Member Function Documentation
static int simplesearch::max (const int & a, const int & b) [inline, static, private]
Referenced by search().
static int simplesearch::min (const int & a, const int & b) [inline, static, private]
Referenced by search().
void simplesearch::search (char *const _s, const int _length, const int _debug) [inline]
References al, aligner< T >::align(), corpus, g, heap, max(), min(), golem::read(), aligner< T >::score, and SEMILOCAL.
Member Data Documentation
aligner<int>* simplesearch::al [private]
Referenced by search(), simplesearch(), and ~simplesearch().
string simplesearch::corpus [private]
Referenced by search(), and simplesearch().
golem* simplesearch::g [private]
Referenced by search().
priority_queue<aligner<int>::alin*,vector<aligner<int>::alin*>, comparator> simplesearch::heap [private]
Referenced by search().
The documentation for this class was generated from the following file:
simplesearch.h