FreeLing: senses Class Reference
senses Class Reference
Class senses implements a sense annotator.
#include <senses.h>
Public Member Functions
senses (const std::string &, bool)
Constructor.
~senses ()
Destructor.
void analyze (std::list< sentence > &)
sense annotate selected analysis for each word in given sentences
std::list< sentence > analyze (const std::list< sentence > &)
sense annotate selected analysis for each word in given sentence, return copy (useful for python API)
Private Attributes
semanticDB * semdb
bool duplicate
flag to remember whether analysis are duplicated for each possible sense
Detailed Description
Class senses implements a sense annotator.
Constructor & Destructor Documentation
senses::senses (const std::string & , bool)
Constructor.
senses::~senses ()
Destructor.
References semdb.
Member Function Documentation
std::list< sentence > senses::analyze (const std::list< sentence > & ls)
sense annotate selected analysis for each word in given sentence, return copy (useful for python API)
Analyze given sentences.
Return analyzed copy.
References analyze().
void senses::analyze (std::list< sentence > & ls)
sense annotate selected analysis for each word in given sentences
Analyze given sentences.
References duplicate, semanticDB::get_word_senses(), semdb, and TRACE.
Referenced by analyze().
Member Data Documentation
bool senses::duplicate [private]
flag to remember whether analysis are duplicated for each possible sense
Referenced by analyze().
semanticDB* senses::semdb [private]
Referenced by analyze(), and ~senses().
The documentation for this class was generated from the following files:
senses.h
senses.cc