FreeLing: check_asynon Class Reference
check_asynon Class Reference
lemma or any ancestor has given synonym
#include <dep_rules.h>
Public Member Functions
check_asynon (semanticDB &, const std::string &, const std::string &)
bool eval (dep_tree::iterator) const
eval whether a single node matches a condition only called from check if needed.
Private Attributes
semanticDB & semdb
Detailed Description
lemma or any ancestor has given synonym
Constructor & Destructor Documentation
check_asynon::check_asynon (semanticDB & , const std::string & , const std::string &)
Member Function Documentation
bool check_asynon::eval (dep_tree::iterator n) const [virtual]
eval whether a single node matches a condition only called from check if needed.
The abstract class version should never be reached.
Reimplemented from rule_expression.
References rule_expression::find_any(), semanticDB::get_sense_info(), semanticDB::get_word_senses(), sense_info::parents, semdb, and sense_info::words.
Member Data Documentation
semanticDB& check_asynon::semdb [private]
Referenced by eval().
The documentation for this class was generated from the following files:
dep_rules.h
dep_rules.cc