#!/bin/bash

#
# sample script to fake the Simple PreProcessing Protocol (use with the SRG)
#

user=${USER}
if [ -z "${user}" ]; then user=$(whoami); fi

if [ -f ${HOME}/.freelingrc ]; then
  . ${HOME}/.freelingrc
fi

if [ -z "${FREELINGANALYZER}" ]; then
  export FREELINGANALYZER=${LOGONROOT}/upc/bin/LKBanalyzer
fi
if [ -z "${FREELINGCFG}" ]; then
  export FREELINGCFG=${LOGONROOT}/upf/srg/freeling/logon.cfg
fi
if [ -z "${FREELINGSHARE}" ]; then
  export FREELINGSHARE=${LOGONROOT}/upc/FreeLing
fi

#
# when running as part of the LOGON tree, FreeLing is part of the same tree,
# i.e. there is no need to have additional tools installed locally.  ideally,
# the LOGON tree (including the SRG) will be functional an a wide rage of Linux
# distributions, not assuming any non-standard additional packages.
#
cd ${LOGONROOT};
exec ${FREELINGANALYZER} -f ${FREELINGCFG} 2> /tmp/freeling.debug.${user};
