#!/bin/bash

#  usage:
#
#   analyze [options] 
#
#  Executes freeling analyzer with given options, taking care of
#  paths and default locations
# 
#  This script also checks whether the config file given with option -f
#  is found in the current directory. If not, it is searched in
#  share/FreeLing/config under FreeLing installation directory.


## Execute FreeLing environment initialization
. $(dirname $(readlink -e $0))/initialize $@

## call actual executable
if [[ "x$1" == "x-"* ]]; then
  # if first parameter is an option (e.g. -f, --nodates, etc)
  # use normal interactive mode
  $FREELING/bin/analyzer $param
else
  # if first parameter is NOT an option, assume
  # it's a name for a pipe and start in client/server mode
  echo "First parameter '$1' is not an option. Starting server mode."
  echo "You can now analyze text with: "
  echo "      analyzer_client $1  <input.txt >output.txt"
  echo ""
  $FREELING/bin/analyzer_server $param
fi




